imports:
    - { resource: config.yml }

#doctrine:
#    metadata_cache_driver: apc
#    result_cache_driver: apc
#    query_cache_driver: apc

#monolog:
#    handlers:
#        main:
#            type:         fingers_crossed
#            action_level: error
#            handler:      nested
#        nested:
#            type:  stream
#            path:  %kernel.logs_dir%/%kernel.environment%.log
#            level: debug

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      grouped
        grouped:
            type:    group
            members: [nested, buffered]
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug        
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: errores@cuentalo.com.uy
            to_email:   bugs@cuentalo.com.uy
            subject:    Ocurrió un error!!!
            level:      critical