MondelCuentaloBundle:
    resource: "@MondelCuentaloBundle/Resources/config/routing.yml"
    prefix:   /

MondelSiteBundle:
    resource: "@MondelSiteBundle/Resources/config/routing.yml"
    prefix:   /	

MondelUserBundle:
    resource: "@MondelUserBundle/Resources/config/routing.yml"
    prefix:   /usuario/

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
