security:
    encoders:        
        Mondel\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: Mondel\UserBundle\Entity\User, property: email }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /usuario/ingresar
                check_path:  /usuario/ingresar_chequeo
                use_referer: true
            logout:
                path:   /usuario/salir
                target: /
            remember_me:
                key:      7869b2fa4458aaa7786e39d10410d5f3cd
                lifetime: 3600
                path:     /
                domain:   ~                
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ingresar, roles: IS_AUTHENTICATED_ANONYMOUSLY }