jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Mondel\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: Mondel\UserBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #login:
        #    pattern:  ^/usuario/ingresar$
        #    security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /usuario/ingresar_chequeo
                login_path: /usuario/ingresar
            logout:
                path:   /usuario/salir
                target: /
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/ingresar, roles: IS_AUTHENTICATED_ANONYMOUSLY }