<?php

namespace Mondel\CuentaloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificacionRepository extends EntityRepository
{
}