<?php

namespace Mondel\CuentaloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
	public function tieneNotificacionesSinLeer($idUsuario)
	{
		$usuario = $this->find($idUsuario);

		foreach ($usuario->getContenidoSuscripciones() as $suscripcion) {
			foreach ($suscripcion->getNotificaciones() as $notificacion) {
				if (!$notificacion->getLeida()) {
					return true;
				}
			}
		}
		return false;
    }

    public function obtenerNotificaciones($idUsuario)
	{
		$usuario = $this->find($idUsuario);

		$notificaciones = array();

		foreach ($usuario->getContenidoSuscripciones() as $suscripcion) {
			foreach ($suscripcion->getNotificaciones() as $notificacion) {
				array_push($notificaciones, $notificacion);
			}
		}
		
		return $notificaciones;
    }

    public function estaSuscritoContenido($idUsuario, $idContenido)
	{
		$usuario = $this->_em->createQuery('SELECT u FROM MondelCuentaloBundle:Usuario u WHERE u.id = '.$idUsuario)->getSingleResult();
    	$contenido = $this->_em->createQuery('SELECT c FROM MondelCuentaloBundle:Contenido c WHERE c.id = '.$idContenido)->getSingleResult();

		return count($this->_em->createQuery('SELECT s FROM MondelCuentaloBundle:UsuarioContenidoSuscripcion s WHERE s.usuario = :usuario and s.contenido = :contenido')->setParameters(array(
				'usuario'=>$usuario, 
				'contenido'=>$contenido
				))->getArrayResult()) > 0;
    }

    public function marcarNotificacionesComoLeidas($idUsuario, $idContenido)
    {
    	$usuario = $this->_em->createQuery('SELECT u FROM MondelCuentaloBundle:Usuario u WHERE u.id = '.$idUsuario)->getSingleResult();
    	$contenido = $this->_em->createQuery('SELECT c FROM MondelCuentaloBundle:Contenido c WHERE c.id = '.$idContenido)->getSingleResult();

	    $suscripcion = $this->_em->createQuery('SELECT s FROM MondelCuentaloBundle:UsuarioContenidoSuscripcion s WHERE s.usuario = :usuario and s.contenido = :contenido')->setParameters(array(
				'usuario'=>$usuario, 
				'contenido'=>$contenido
				))->getSingleResult();

		if ($suscripcion != null) {
		    foreach ($suscripcion->getNotificaciones() as $notificacion) {		    	
		    	$notificacion->setLeida(true);	    	
		    }
		    $this->_em->flush();
		}
    }

}