post_create:
    pattern:  /crear
    defaults: { _controller: MondelPostBundle:Default:create }

post_show_category:
    pattern:  /mostrar/{categoryName}
    defaults: { _controller: MondelPostBundle:Default:showCategoryPosts }

post_page:
    pattern:  /{postId}
    defaults: { _controller: MondelPostBundle:Default:showPostPage }
    requirements:  { postId: \d+ }

comment_create:
    pattern:  /{postId}/comentar
    defaults: { _controller: MondelPostBundle:Comment:create }