parameters:
#    mondel_post.example.class: Mondel\PostBundle\Example

services:
#    mondel_post.example:
#        class: %mondel_post.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
