_inicio:
    pattern:  /
    defaults: { _controller: MondelCuentaloBundle:Default:inicio }

_ingresar:
    pattern:  /ingresar
    defaults: { _controller: MondelCuentaloBundle:Usuario:ingreso }

_ingresar_chequeo:
    pattern:  /ingresar_chequeo

_salir:
    pattern:  /salir

_registrar:
    pattern:  /registrarme
    defaults: { _controller: MondelCuentaloBundle:Usuario:registro }

# usuario

_contrasenia_recuperar:
    pattern:  /recuperar/contraseña
    defaults: { _controller: MondelCuentaloBundle:Usuario:recuperarContrasenia }

_usuario_activacion:
    pattern:  /usuario/activar/{token}
    defaults: { _controller: MondelCuentaloBundle:Usuario:usuarioActivacion }

# contenido

_contenido_crear:
    pattern:  /contenido/crear
    defaults: { _controller: MondelCuentaloBundle:Contenido:crear }
    requirements: { _method: POST }

_contenido_mostrar:
    pattern:  /contenido/{id}
    defaults:  { _controller: MondelCuentaloBundle:Contenido:mostrar }

_contenido_comentar:
    pattern:  /contenido/{id}/comentar
    defaults:  { _controller: MondelCuentaloBundle:Contenido:comentar }
    requirements: { _method: POST }

###########

vista_contenido:
    pattern:  /tipo/id
    defaults: { _controller: MondelCuentaloBundle:Contenido:mostrar }