inicio:
    pattern:  /
    defaults: { _controller: MondelCuentaloBundle:Default:index }

login:
    pattern:  /ingresar
    defaults: { _controller: MondelCuentaloBundle:Usuario:login }

login_check:
    pattern:  /login_check

logout:
    pattern:  /salir

registro:
    pattern:  /registro
    defaults: { _controller: MondelCuentaloBundle:Usuario:registro }

recuperar_contrasenia:
    pattern:  /recuperar
    defaults: { _controller: MondelCuentaloBundle:Usuario:recuperarContrasenia }

usuario_activacion:
    pattern:  /activar/{token}
    defaults: { _controller: MondelCuentaloBundle:Usuario:registroActivar }

vista_contenido:
    pattern:  /tipo/id
    defaults: { _controller: MondelCuentaloBundle:Contenido:mostrar }