_inicio:
    pattern:  /
    defaults: { _controller: MondelCuentaloBundle:Default:inicio }

_ingresar:
    pattern:  /ingresar
    defaults: { _controller: MondelCuentaloBundle:Usuario:ingreso }

_ingresar_chequeo:
    pattern:  /ingresar_chequeo

_salir:
    pattern:  /salir

_registrar:
    pattern:  /registrarme
    defaults: { _controller: MondelCuentaloBundle:Usuario:registro }

_pagina:
    pattern:  /pagina/{pagina}
    defaults: { _controller: MondelCuentaloBundle:Default:pagina }    

# usuario

_contrasenia_recuperar:
    pattern:  /contraseña/recuperar
    defaults: { _controller: MondelCuentaloBundle:Usuario:contraseniaRecuperar }

_contrasenia_cambiar:
    pattern:  /contraseña/cambiar
    defaults: { _controller: MondelCuentaloBundle:Usuario:contraseniaCambiar }

_usuario_activacion:
    pattern:  /usuario/activar/{token}
    defaults: { _controller: MondelCuentaloBundle:Usuario:usuarioActivacion }

_usuario_eliminar:
    pattern:  /usuario/eliminar
    defaults: { _controller: MondelCuentaloBundle:Usuario:usuarioEliminar }

_contacto:
    pattern:  /contacto
    defaults: { _controller: MondelCuentaloBundle:Default:contacto }  

# contenido

_contenido_crear:
    pattern:  /contenido/crear
    defaults: { _controller: MondelCuentaloBundle:Contenido:crear }
    requirements: { _method: POST }

_contenido_mostrar:
    pattern:  /contenido/{id}/mostrar
    defaults:  { _controller: MondelCuentaloBundle:Contenido:mostrar }

_contenido_pagina_mostrar:
    pattern:  /contenido/{id}
    defaults:  { _controller: MondelCuentaloBundle:Contenido:paginaMostrar }
    requirements:  { id: \d+ }

_contenido_comentar:
    pattern:  /contenido/{id}/comentar
    defaults:  { _controller: MondelCuentaloBundle:Contenido:comentar }    
    
_contenido_listar:
    pattern:  /contenido/{categoria}/{inicio}/{cantidad}
    defaults:  { _controller: MondelCuentaloBundle:Contenido:listar }
    requirements: { inicio: \d+, cantidad: \d+ }    

_contenido_categoria_listar:
    pattern:  /{categoria}
    defaults:  { _controller: MondelCuentaloBundle:Contenido:categoriaListar }

_comentario_eliminar:
    pattern:  /comentario/{id}/eliminar
    defaults:  { _controller: MondelCuentaloBundle:Contenido:comentarioEliminar }
    requirements: { id: \d+ }

###########

  
