homepage:
    pattern:  /
    defaults: { _controller: MondelCuentaloBundle:Default:index }

login:
    pattern:  /login
    defaults: { _controller: MondelCuentaloBundle:Usuario:login }

login_check:
    pattern:  /login_check

logout:
    pattern:  /logout

registro:
    pattern:  /registro
    defaults: { _controller: MondelCuentaloBundle:Usuario:registro }

recuperar_contrasenia:
    pattern:  /recuperar
    defaults: { _controller: MondelCuentaloBundle:Usuario:recuperarContrasenia }

usuario_activacion:
    pattern:  /activar/{token}
    defaults: { _controller: MondelCuentaloBundle:Usuario:registroActivar }