homepage:
    pattern:  /
    defaults: { _controller: MondelCuentaloBundle:Default:index }

login:
    pattern:  /login
    defaults: { _controller: MondelCuentaloBundle:Usuario:login }

login_check:
    pattern:  /login_check

logout:
    pattern:  /logout

registro:
    pattern:  /registro
    defaults: { _controller: MondelCuentaloBundle:Usuario:registro }

vista_contenido:
    pattern:  /{tipo}/{id}
    defaults: { _controller: MondelCuentaloBundle:Contenido:mostrar }

vista_mensajes:
    pattern:  /mensajes
    defaults: { _controller: MondelCuentaloBundle:Default:index, tipo: m }

vista_anecdotas:
    pattern:  /anecdotas
    defaults: { _controller: MondelCuentaloBundle:Default:index, tipo: a }

vista_secretos:
    pattern:  /secretos
    defaults: { _controller: MondelCuentaloBundle:Default:index, tipo: s }

recuperar_contrasenia:
    pattern:  /recuperar
    defaults: { _controller: MondelCuentaloBundle:Usuario:recuperarContrasenia }

#votar:
#    pattern:  /votar/{id}
#    defaults: { _controller: MondelCuentaloBundle:Contenido:votar }