parameters:
#    mondel_cuentalo.example.class: Mondel\CuentaloBundle\Example

services:
#    mondel_cuentalo.example:
#        class: %mondel_cuentalo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    mondel_cuentalo.twig.extension:
        class: Mondel\CuentaloBundle\Twig\Extensions\MondelCuentaloExtension
        tags:
            - { name: twig.extension }
