user_login:
    pattern:  /ingresar
    defaults: { _controller: MondelUserBundle:Default:login }

user_login_check:
    pattern: /ingresar_chequeo

user_logout:
    pattern: /salir

user_register:
    pattern:  /registro
    defaults: { _controller: MondelUserBundle:Default:register }

user_password_recover:
    pattern:  /recuperar
    defaults: { _controller: MondelUserBundle:Default:passwordRecover }

user_activation:
    pattern:  /activar/{token}
    defaults: { _controller: MondelUserBundle:Default:activateUser }

user_change_password:
    pattern:  /cambiar/contrasenia
    defaults: { _controller: MondelUserBundle:Default:passwordChange }

user_delete:
    pattern:  /eliminar
    defaults: { _controller: MondelUserBundle:Default:userDelete }