login:
    pattern:  /ingresar
    defaults: { _controller: MondelUserBundle:Default:login }

login_check:
    pattern: /ingresar_chequeo

logout:
    pattern: /salir

register:
    pattern:  /registro
    defaults: { _controller: MondelUserBundle:Default:register }