parameters:
#    mondel_user.example.class: Mondel\UserBundle\Example

services:
#    mondel_user.example:
#        class: %mondel_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
