static_page:
    pattern:  /sitio/{page}
    defaults: { _controller: MondelSiteBundle:Default:staticPage }

home_page:
    pattern: /
    defaults: { _controller: MondelSiteBundle:Default:homePage }
